apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskappDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldflask
  template:
    metadata:
      labels:
        app: helloworldflask
    spec:
      containers:
      - name: helloworldflask
        image: 192.168.2.54:5000/hello-world-flask
        ports:
        - containerPort: 6666
